# Deploy Stacker News bot to fly.io
# You can run flyctl launch to create fly.toml, then you can refer to this file to modify it

app = "stackernews"                             # set your app name on fly.io
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "paketobuildpacks/builder:full"     # need full for sqlite

[env]
  DB_TYPE = "redis"                             # redis or sqlite
  DB_NAME = "sqlite:///db/stacker.db"           # you can create volume on fly.io for permanent storage, need if DB_TYPE is sqlite
  REDIS_URL = "redis://default:XXXX@name/0"     # replace with your redis url and database number, need if DB_TYPE is redis
  LOG_NAME = "StackerNews"
  LOG_FILE = "log/stacker-news-top.log"
  TG_CHAT_ID = "-1001234567890"                 # Telegram chat id or group id for receiving message
  TG_TOKEN = "123456789:XXXX"                   # Your Telegram bot token

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[processes]
  stacker = "python3 app.py"

[[services]]
  http_checks = []
  processes = ["stacker"]

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
